set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
set(CMAKE_POLICY_DEFAULT_CMP0135 NEW)
cmake_minimum_required(VERSION 3.18)

set(RENDERER_PROJECT "Renderer")

project(${RENDERER_PROJECT} CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Vulkan REQUIRED)

if(MSVC)
    set(CMAKE_GENERATOR_PLATFORM ${CMAKE_VS_PLATFORM_NAME})
    set(CMAKE_BUILD_TYPE Debug)
endif()

set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
set(CMAKE_DEBUG_POSTFIX "" CACHE BOOL "" FORCE)
set(LIBRARY_SUFFIX "" CACHE BOOL "" FORCE)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}/${CMAKE_GENERATOR_PLATFORM})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}/${CMAKE_GENERATOR_PLATFORM})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}/${CMAKE_GENERATOR_PLATFORM})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}/${CMAKE_GENERATOR_PLATFORM})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG ${CMAKE_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}/${CMAKE_GENERATOR_PLATFORM})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE ${CMAKE_SOURCE_DIR}/bin/${CMAKE_SYSTEM_NAME}/${CMAKE_GENERATOR_PLATFORM})

file(
    GLOB_RECURSE RENDERER_BINS_LIST
    "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/bins/*.*"
)

file(
    GLOB_RECURSE RENDERER_LIBS_LIST
    "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libs/*.*"
)

foreach (BIN_FILE ${RENDERER_BINS_LIST})
    file(COPY ${BIN_FILE} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endforeach()

foreach (LIB_FILE ${RENDERER_LIBS_LIST})
    file(COPY ${LIB_FILE} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endforeach()

file(
    GLOB_RECURSE RENDERER_BIULD_LIBS
    "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}*.lib"
)

if(WIN32)
    execute_process(COMMAND python "${CMAKE_CURRENT_SOURCE_DIR}/shaders/build_shaders.py")
else()
    execute_process(COMMAND python3 "${CMAKE_CURRENT_SOURCE_DIR}/shaders/build_shaders.py")
endif()

file(
    GLOB_RECURSE RENDERER_SHADERS_LIST
    "${CMAKE_CURRENT_SOURCE_DIR}/shaders/*.spv"
)

foreach (SHADER_FILE ${RENDERER_SHADERS_LIST})
    file(COPY ${SHADER_FILE} DESTINATION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Shaders")
endforeach ()

file(
    GLOB_RECURSE RENDERER_CODE_LIST
    LIST_DIRECTORIES false
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c*"
    "${CMAKE_CURRENT_SOURCE_DIR}/include/renderer/*.h*"
    "${CMAKE_CURRENT_SOURCE_DIR}/include/renderer/*.inl"
)

add_library(${RENDERER_PROJECT} SHARED ${RENDERER_CODE_LIST})

target_compile_features(${RENDERER_PROJECT} PUBLIC cxx_std_20)
target_include_directories(${RENDERER_PROJECT} PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/include
    ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/include
    ${Vulkan_INCLUDE_DIRS}
)
target_link_libraries(${RENDERER_PROJECT} PUBLIC ${RENDERER_BIULD_LIBS} ${Vulkan_LIBRARIES})

foreach(RENDERER_FILE IN ITEMS ${RENDERER_CODE_LIST})
    get_filename_component(RENDERER_FILE_PATH "${RENDERER_FILE}" PATH)
    file(RELATIVE_PATH RENDERER_FILE_RELATIVE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/" "${RENDERER_FILE_PATH}")
    string(REPLACE "\\" "/" GROUP_PATH "${RENDERER_FILE_RELATIVE_PATH}")
    file(RELATIVE_PATH EXTERNAL_INCLUDE_RELATIVE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/" "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/include")
    string(REPLACE ${EXTERNAL_INCLUDE_RELATIVE_PATH} "" GROUP_PATH "${GROUP_PATH}")
    string(REPLACE "src" "" GROUP_PATH "${GROUP_PATH}")
    string(REPLACE "include/renderer" "" GROUP_PATH "${GROUP_PATH}")
    source_group("${GROUP_PATH}" FILES "${RENDERER_FILE}")
endforeach()
