set(RENDERER_PROJECT "Renderer")

find_package(Vulkan REQUIRED)

file(
    GLOB_RECURSE RENDERER_BINS_LIST
    "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/bins/*.*"
)

file(
    GLOB_RECURSE RENDERER_LIBS_LIST
    "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/libs/*.*"
)

foreach (BIN_FILE ${RENDERER_BINS_LIST})
    file(COPY ${BIN_FILE} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endforeach ()

foreach (LIB_FILE ${RENDERER_LIBS_LIST})
    file(COPY ${LIB_FILE} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endforeach ()

execute_process(COMMAND python3 "${CMAKE_CURRENT_SOURCE_DIR}/shaders/build_shaders.py")

file(
    GLOB_RECURSE RENDERER_SHADERS_LIST
    "${CMAKE_CURRENT_SOURCE_DIR}/shaders/*.spv"
)

foreach (SHADER_FILE ${RENDERER_SHADERS_LIST})
    file(COPY ${SHADER_FILE} DESTINATION "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Shaders")
endforeach ()

file(
    GLOB_RECURSE RENDERER_CODE_LIST
    LIST_DIRECTORIES false
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c*"
    "${CMAKE_CURRENT_SOURCE_DIR}/include/renderer/*.h*"
    "${CMAKE_CURRENT_SOURCE_DIR}/include/renderer/*.inl"
)

add_library(${RENDERER_PROJECT} SHARED ${RENDERER_CODE_LIST})

target_compile_features(${RENDERER_PROJECT} PRIVATE cxx_std_20)
target_include_directories(${RENDERER_PROJECT} PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/include
    ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/include
    ${Vulkan_INCLUDE_DIRS}
)
target_link_libraries(${RENDERER_PROJECT} PRIVATE ${RENDERER_BINS_LIST} ${Vulkan_LIBRARIES})

foreach(RENDERER_FILE IN ITEMS ${RENDERER_CODE_LIST})
    get_filename_component(RENDERER_FILE_PATH "${RENDERER_FILE}" PATH)
    file(RELATIVE_PATH RENDERER_FILE_RELATIVE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/" "${RENDERER_FILE_PATH}")
    string(REPLACE "\\" "/" GROUP_PATH "${RENDERER_FILE_RELATIVE_PATH}")
    file(RELATIVE_PATH EXTERNAL_INCLUDE_RELATIVE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/" "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/include")
    string(REPLACE ${EXTERNAL_INCLUDE_RELATIVE_PATH} "" GROUP_PATH "${GROUP_PATH}")
    string(REPLACE "src" "" GROUP_PATH "${GROUP_PATH}")
    string(REPLACE "include/renderer" "" GROUP_PATH "${GROUP_PATH}")
    source_group("${GROUP_PATH}" FILES "${RENDERER_FILE}")
endforeach()
